export const CLEANUP_ROOMS = ['Living Room', 'Kitchen', 'Bedroom', 'Hallway'];

// The host reviews the jobs before play and removes jobs that do not fit the home.
export const CLEANUP_TASKS = {
    any: [
        'Return three misplaced items to their usual places',
        'Put away one item that belongs in another room',
        'Put loose paper into its folder or recycling bin',
        'Clear one small surface and put its items away',
        'Straighten the items on one shelf',
        'Put a bag or basket back in its usual place',
        'Collect three small pieces of litter and put them in the bin',
        'Put away a game, puzzle, or craft that nobody is using',
        'Put a loose charger or cable in its storage spot',
        'Wipe a dusty shelf with a dry cloth',
        'Clear one small section of the floor',
        'Put one empty box in the recycling bin',
    ],
    'Living Room': [
        'Put the sofa cushions back in place',
        'Fold a blanket and put it in its usual place',
        'Return the remote controls to their usual spot',
        'Put three toys in their storage box',
        'Return three books to the shelf',
        'Put a board game back in its box',
        'Clear the coffee table of items that belong elsewhere',
        'Straighten the rug',
    ],
    Kitchen: [
        'Wipe crumbs off a small section of the table with a damp cloth',
        'Put three clean spoons in the cutlery drawer',
        'Put three clean plastic cups in their usual place',
        'Put the placemats in their usual place',
        'Push the chairs neatly under the table',
        'Return the clean dish towel to its hook',
        'Put away the reusable grocery bags',
        'Clear the table of items that belong in another room',
    ],
    Bedroom: [
        'Pull the duvet or blanket neatly over the bed',
        'Put the pillows back at the head of the bed',
        'Put three pieces of dirty clothing in the hamper',
        'Fold a pair of pajamas and put them away',
        'Pair three sets of clean socks',
        'Return three toys to their storage spot',
        'Put the books beside the bed back on the shelf',
        'Clear the top of the bedside table',
    ],
    Hallway: [
        'Put three pairs of shoes neatly in their usual place',
        'Hang a coat on its hook',
        'Put a backpack in its usual place',
        'Straighten the doormat',
        'Put a hat or scarf in its storage spot',
        'Put unopened mail in the family mail spot',
        'Return a set of keys to its usual place',
        'Clear an item off the path to the door',
    ],
};
